//user
export const SAVE_USER_CREDENTIALS = "SAVE_USER_CREDENTIALS";
export const DELETE_USER_CREDENTIALS = "DELETE_USER_CREDENTIALS";

//comunicazioni
export const FETCH_COMUNICAZIONI_START = "FETCH_COMUNICAZIONI_START";
export const FETCH_COMUNICAZIONI_SUCCESS = "FETCH_COMUNICAZIONI_SUCCESS";
export const FETCH_COMUNICAZIONI_ERROR = "FETCH_COMUNICAZIONI_ERROR";

export const REFRESH_COMUNICAZIONI_START = "REFRESH_COMUNICAZIONI_START"
export const REFRESH_COMUNICAZIONI_SUCCESS = "REFRESH_COMUNICAZIONI_SUCCESS"
export const REFRESH_COMUNICAZIONI_ERROR = "REFRESH_COMUNICAZIONI_ERROR"

export const POST_COMUNICAZIONE_START = "POST_COMUNICAZIONE_START";
export const POST_COMUNICAZIONE_SUCCESS = "POST_COMUNICAZIONE_SUCCESS";
export const POST_COMUNICAZIONE_ERROR = "POST_COMUNICAZIONE_ERROR";

//TODO: Gestire errori rimozione comunicazione
export const REMOVE_ONE_COMUNICAZIONE = "REMOVE_ONE_COMUNICAZIONE"


//assenze
export const FETCH_ASSENZE_START = "FETCH_ASSENZE_START";
export const FETCH_ASSENZE_SUCCESS = "FETCH_ASSENZE_SUCCESS";
export const FETCH_ASSENZE_ERROR = "FETCH_ASSENZE_ERROR";


//proposte
export const POST_PROPOSTA_START = "POST_PROPOSTA_START";
export const POST_PROPOSTA_SUCCESS = "POST_PROPOSTA_SUCCESS";
export const POST_PROPOSTA_ERROR = "POST_PROPOSTA_ERROR";
export const FETCH_PROPOSTE_START = "FETCH_PROPOSTE_START";
export const FETCH_PROPOSTE_SUCCESS = "FETCH_PROPOSTE_SUCCESS";
export const FETCH_PROPOSTE_ERROR = "FETCH_PROPOSTE_ERROR";