//comunicazioni
export const FETCH_COMUNICAZIONI_START = "FETCH_COMUNICAZIONI_START";
export const FETCH_COMUNICAZIONI_SUCCESS = "FETCH_COMUNICAZIONI_SUCCESS";
export const FETCH_COMUNICAZIONI_ERROR = "FETCH_COMUNICAZIONI_ERROR";
// export const ADD_COMUNICAZIONE = "ADD_COMUNICAZIONE";
// export const DELETE_COMUNICAZIONE = "DELETE_COMUNICAZIONE";

//assenze
export const FETCH_ASSENZE_START = "FETCH_ASSENZE_START";
export const FETCH_ASSENZE_SUCCESS = "FETCH_ASSENZE_SUCCESS";
export const FETCH_ASSENZE_ERROR = "FETCH_ASSENZE_ERROR";
